config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
            sessions: "users/sessions",
            registrations: "users/registrations",
            omniauth_callbacks: "users/omniauth_callbacks",
          }

  resources :users, only: :show do
    resources :goals
    resources :connections
    resources :preferences, except: [:index]
  end

  resources :users, only: :index

  resources :communities, only: [:show, :index]

  post "/motimates", to: "connections#accept", as: :accept

  get "connections/:id", to: "connections#show"
  get "users/:id/motimates", to: "motimates#motimates_for_user"

  delete "/users/:id/delete_avatar", to: "users#delete_avatar", as: :delete_avatar

  root "welcome#home"
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :goals
  has_many :users, through: :goals
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  load_resource
  def index

  end

  def show

  end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/index.html.erb
<h1>Communities</h1>

<% @communities.all.each do |community| %>
  <%= content_tag :div do %>
    <%= link_to community.name, community_path(community) %>
  <% end %>
<% end %>

app/views/communities/show.html.erb
<h1><%= @community.name.humanize %> community page</h1>
<h3><%= @community.description %></h3>
<p><%= link_to "Add a goal in this community", new_user_goal_path(current_user, community_id: @community.id) if user_signed_in? %></p>
<h4>Here are some goals people have:</h4>
<dl class="">
  <% @community.goals.take(5).each do |goal| %>
    <dt><%= goal.name %></dt>
    <dd><%= goal.description %></dd>
    <br>
  <% end %>
</dl>