config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
            sessions: "users/sessions",
            registrations: "users/registrations",
            omniauth_callbacks: "users/omniauth_callbacks",
          }

  resources :users, only: :show do
    resources :goals
    resources :connections
    resources :preferences, except: [:index]
  end

  resources :users, only: :index

  resources :communities, only: [:show, :index]

  post "/motimates", to: "connections#accept", as: :accept

  get "connections/:id", to: "connections#show"
  get "users/:id/motimates", to: "motimates#motimates_for_user"

  delete "/users/:id/delete_avatar", to: "users#delete_avatar", as: :delete_avatar

  root "welcome#home"
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: "flash " << flash_class_name(name) %>
<% end %>
<% if devise_controller? and resource && resource.errors.any? %>
  <%= content_tag :div, class: "flash " << flash_class_name("alert") do %>
    <% resource.errors.full_messages.each do |msg| %>
      <%= content_tag :p, msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div class="ui small modal">
  <i class="close icon"></i>
  <div class="header">
    Motimate request
  </div>
  <div class="image content">
    <div class="ui middle aligned rounded image">
      <% if @user.avatar.attached? %>
        <% if @user.avatar.variable? %>
          <%= image_tag(@user.avatar.variant(resize: "400x400!")) %>
        <% else %>
          <%= image_tag(gravatar_image_url(@user.email, size: 400), height: 400, width: 400) %>
        <% end %>
      <% else %>
        <%= image_tag gravatar_image_url(@user.email, size: 400), height: 400, width: 400 %>
      <% end %>
    </div>
    <div class="description">
      <div class="ui header">People will be more likely to add you if you leave a custom note.</div>
      <p>Optionally write a note, then click send to complete your request.</p>
      <%= form_with(url: user_connections_path(current_user.id, motimate_id: @user.id), id: "modal-form", class: "ui form", remote: "local") do |f| %>
        <%= f.text_area :note, class: "field" %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <div class="ui pink cancel button">
      Cancel
    </div>
    <input type="submit" value="Send" form="modal-form" class="ui teal approve button">
  </div>
</div>

app/views/layouts/_motimate_requests.html.erb
<div class="ui comments">
  <% if current_user.motimate_requests.empty? %>
    <div class="comment item">
      <div class="text">
        You have no motimate requests
      </div>

    </div>
  <% else %>
    <% current_user.motimate_requests.each do |moti| %>
      <div class="request comment item">
        <% if moti.avatar.attached? %>
          <% if moti.avatar.variable? %>
            <%= image_tag(moti.avatar.variant(resize: "40x40!"), class: "avatar") %>
          <% else %>
            <%= image_tag(gravatar_image_url(moti.email, size: 40), height: 40, width: 40, class: "avatar") %>
          <% end %>
        <% else %>
          <%= image_tag gravatar_image_url(moti.email, size: 40), height: 40, width: 40, class: "avatar" %>
        <% end %>
        <div class="content">
          <%= link_to moti.name, user_path(moti), class: "author" %>
          <div class="text connection">
            <%= Connection.note_for(current_user, moti) %>
          </div>
          <div class="actions">
            <a rel="nofollow" class="js-accept" data-user-id="<%= current_user.id %>" data-motimate-id="<%= moti.id %>">accept</a>
            <a rel="nofollow" class="js-deny" data-user-id="<%= current_user.id %>" data-motimate-id="<%= moti.id %>">deny</a>

          </div>
        </div>
      </div>
      <div class="ui fitted divider"> </div> <% end %> <% end %> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Motimates</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="ui large teal inverted borderless fixed menu">
      <a href="/" class="ui item"><%= image_tag "motimates_logo.png", :alt => "Motimates logo", :class => "ui mini middle aligned image" %></a>
      <div class="ui simple dropdown item">
        <span class="text">Browse</span>
        <i class="dropdown icon"></i>
        <div class="menu">
          <% if user_signed_in? %>
            <%= link_to "Motimates", users_path, :class => "item" %>
            <%= link_to "Goals", user_goals_path(current_user), :class => "item" %>
          <% end %>
          <%= link_to "Communitites", communities_path, :class => "item" %>
        </div>
      </div>
      <% unless user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path, :class => "right item" %>
        <%= link_to "Log In", new_user_session_path, :class => "item" %>
      <% else %>
        <div class="ui right simple dropdown item">
          <i class="large icons">
            <i class="users icon"></i>
            <%= content_tag(:i, '', id: "request-icon", class: "bottom right corner pink circle icon") unless current_user.motimate_requests.empty? %>
          </i>
          <div class="menu">
            <%= render "layouts/motimate_requests" %>
          </div>
        </div>
        <%= link_to "Profile", user_path(current_user), :class => "item" %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "item" %>
      <% end %>
    </nav>
    <div class="ui main container">
      <%= render "layouts/flash_message" %>
      <div id="modal-container">
        <%= render "layouts/modal" if @user && user_signed_in? %>
      </div>
      <%= yield %>
    </div>
    <footer>
      <div class="ui horizontal bulleted link list">
        <a class="item">
          Motimates
        </a>
        <a class="item">
          Terms and Conditions 
        </a>
        <a class="item">
          Privacy Policy
        </a>
        <a class="item">
          Contact Us
        </a>
      </div>
    </footer>
  </body>
</html>